### ISSUE TITLE
SnackBar shows Warning even when it shouldn't

### ISSUE THREAD

**Issue by Mukazuge** [rcgonzalezf/weather-app-demo#53]
when opening the App or changing the temperature units in Settings, the App keeps notifying that there is no Location Access. 
![snackbar_ bug_proof](https://cloud.githubusercontent.com/assets/8145868/19334287/1ddc4350-90b8-11e6-81ab-f77734ec3e5a.jpg)
![weather_demo_snackbar_bug](https://cloud.githubusercontent.com/assets/8145868/19334288/1ddc82b6-90b8-11e6-93f6-f1edb8835b7a.jpg)

**Comment by moxi** [comment]
Maybe one way to get rid of that check is to be able to refresh the screen:
https://github.com/moxi/weather-app-demo/issues/46 still it will be interesting to see what's happening.

**Comment by rcgonzalezf** [comment]
Closing this issue since it has been fixed.
