### ISSUE TITLE
Latest version of the code, doesn't update the forecast list when entering text.

### ISSUE THREAD

**Issue by CynthiaDanyel** [rcgonzalezf/weather-app-demo#66]
When entering a search with text, the Geo location results are still present.

Steps to reproduce:

1. Open the app
1. Click on the (+) fab button. 
1. Portland, US is showed by default.
1. Press OK.

The list doesn't update.

**Comment by rcgonzalezf** [comment]
I'm going to add an espresso test to help with the verification of this flow and use Kotlin instead for the new code.

**Comment by rcgonzalezf** [comment]
The issue was that the endpoint with text wasn't used so it was falling back to the GPS location fetched previously.
